### PR TITLE
Bibliographies and more

### LINKED ISSUE #8: set up checks
Set up github actions to check django code and tests
Would also be good to have it for JS

- [x] Django
- [x] JS
- [x] pre-commit
```[tasklist]
### Tasks
- [ ] https://github.com/UCL-ARC/museum_of_dreams/issues/17
```

### PR DESCRIPTION
**Pull request by acholyn**
Addresses #25  but may need more work - researchers to give feedback on Jan 10th
Closes #8, #33 and #24
Adding to documentation - AWS Chatbot setup
Have added basis for using s3 with CKeditor - to be confirmed on staging. Due to a dependency conflict with boto3, I've downgraded our version of urllib3 from `2.0.4` to `1.26.7` to keep boto3 happy until they update it to work with urllib3 2.0.0

### CODE REVIEW

File: docs/AWSchatbot.md [hunk 1]
```diff
@@ -0,0 +1,18 @@
+# Setting up notifications from AWS to Slack
```
Comment (tcouch) [inline docs/AWSchatbot.md:1]: This looks really interesting, but why is it this project's docs? Isn't this something that would be better in the collaborations group docs?

Comment (tcouch) [reply docs/AWSchatbot.md:1]: Also, what's this for?

**Review by tcouch — COMMENTED** [review]
I've run into a couple of bugs so will stop here. The first is an AttributeError at /admin/mod_app/film/ when I try to create a new film, or view an existing one. It says `'NoneType' object has no attribute 'file'`

I also get RecursionError at /admin/mod_app/analysis/add/ with an error message saying `maximum recursion depth exceeded`

File: mod_app/models/bibliography_model.py [hunk 2]
```diff
@@ -0,0 +1,14 @@
+from django.db import models
+from ckeditor.fields import RichTextField
+
+from mod_app.models import *
```
Comment (tcouch) [inline mod_app/models/bibliography_model.py:4]: This shouldn't be here should it?

Comment (acholyn) [reply mod_app/models/bibliography_model.py:4]: ah - yes thank you

File: docs/AWSchatbot.md (hunk 1 above)
Comment (acholyn) [reply docs/AWSchatbot.md:1]: I suppose I could put it in a collab doc, it's how to set up the notifications that go to the mod-aws channel, which I thought was nicer than emails that will inevitably get lost and is more immediate

File: mod_app/models/bibliography_model.py (hunk 2 above)
Comment (acholyn) [reply mod_app/models/bibliography_model.py]: ah yes- thank you

File: mod_app/admin/film_admin.py [hunk 3]
```diff
@@ -96,6 +98,23 @@ def safe_comments(self, obj):
     safe_comments.allow_tags = True
     safe_comments.short_description = "Comments"
 
+    def preview_video(self, obj):
+        if obj.videos:
```
Comment (tcouch) [inline mod_app/admin/film_admin.py:102]: You have a conflict between the videos property you defined on the Film model (which I think you're referring to here) and the videos related name which is created by the Video class (due to the related_name argument on the film field).

I think the problem is that the related manager is being tested here, which returns True even when there are no videos.

Comment (acholyn) [reply mod_app/admin/film_admin.py]: I've changed it to if `obj.videos.first()` but if it would be better to do it another way that's simple then I'm happy to do that

**Comment by acholyn** [comment]
re. the recursion errors - that's interesting; it's somehow to do with displaying the bibliography as read only? I wonder if it's because it doesn't have one yet? but this error doesn't occur when adding a new film and they should be set up the same way.. 🤔

File: mod_app/admin/film_admin.py (hunk 3 above)
Comment (tcouch) [reply mod_app/admin/film_admin.py]: Why not rename the videos property to something like linked_videos? Otherwise the conflict is still there and it might trip you up in future.

Comment (tcouch) [reply mod_app/admin/film_admin.py]: Actually, I don't think you even need to set a property since obj.videos.all() should be equivalent to what you get with the property.

Comment (tcouch) [reply mod_app/admin/film_admin.py]: Same goes for the rest of the properties on Film pointing to link models: programmes, pub_mats, stills, postcards etc.

File: mod_app/static/css/film.css [hunk 4]
```diff
@@ -0,0 +1,115 @@
...
+  /* justify-content: space-between; */
+  flex-direction: column;
+  align-content: center;
+  margin-left: 0.4rem;
+  > dt {
+    margin: 0.4rem 0;
+  }
+}
+
+.genres {
```
Comment (tcouch) [inline mod_app/static/css/film.css:44]: Did you mean genre? I can't find genres on this page

File: mod_app/static/css/film.css [hunk 5]
```diff
@@ -0,0 +1,115 @@
...
+
+.synopsis {
+  padding: 0.5rem 0;
+  > p {
+    width: 100%;
+    max-inline-size: 100%;
+  }
+}
+
+.cast-credits {
```
Comment (tcouch) [inline mod_app/static/css/film.css:56]: Can't see this anywhere either

File: museum_of_dreams_project/urls.py [hunk 6]
```diff
@@ -41,8 +43,44 @@
         distill_path(
             "", views.HomeView.as_view(), name="home", distill_file="index.html"
         ),
-        distill_path("films/list", views.FilmListView.as_view(), name="film_list"),
-        distill_path("films/<pk>", views.FilmDetailView.as_view(), name="film_detail"),
+        path("favicon.ico", RedirectView.as_view(url="static/admin/img/favicon.ico")),
+        path("mentions-api", views.MentionsApiView.as_view(), name="mentions_api"),
+        # website pages
+        distill_path(
+            "films/list",
```
Comment (tcouch) [inline museum_of_dreams_project/urls.py:50]: I think just films/ rather than films/list would be better, because there's nothing at films/ at the moment.

File: museum_of_dreams_project/urls.py [hunk 7]
```diff
@@ -41,8 +43,44 @@
...
+            views.FilmListView.as_view(),
+            name="film_list",
+        ),
+        distill_path(
+            "films/<pk>",
+            views.FilmDetailView.as_view(),
+            name="film_detail",
+        ),
+        distill_path(
+            "analyses/list",
```
Comment (tcouch) [inline museum_of_dreams_project/urls.py:60]: Same here, why not just analyses/ ?

File: museum_of_dreams_project/urls.py [hunk 8]
```diff
@@ -41,8 +43,44 @@
...
+            views.AnalysisListView.as_view(),
+            name="analysis_list",
+        ),
+        distill_path(
+            "analyses/<pk>",
+            views.AnalysisDetailView.as_view(),
+            name="analysis_detail",
+        ),
+        distill_path(
+            "teaching-resources/list",
```
Comment (tcouch) [inline museum_of_dreams_project/urls.py:70]: teaching-resources/ ?

File: mod_app/templates/film_detail.html [hunk 9]
```diff
@@ -5,8 +5,165 @@
...
+            </label>
+
+
+            <label class="tab-title" for="nonfilmic-tab">Non Filmic
+                <input type="radio" id="nonfilmic-tab" name="tab-group">
+            </label>
+
+            <label class="tab-title" for="bibliography-tab">Bibliography
+                <input type="radio" id="bibliography-tab" name="tab-group">
+            </label>
```
Comment (tcouch) [inline mod_app/templates/film_detail.html:32]: These tabs titles are visible when the page first loads, but only the selected one is visible once I click on one of them.

**Review by tcouch — COMMENTED** [review]
Some general feedback: there's a lot of different stuff here which doesn't really belong in the same PR. This makes it much harder to review.

The list/detail pages outside the admin seem like a work in progress - maybe they could be split out and added later?

File: mod_app/static/css/film.css (hunk 4 above)
Comment (tcouch) [reply mod_app/static/css/film.css:44]: Ignore this, I thought I was looking at the admin page.

File: mod_app/static/css/film.css (hunk 5 above)
Comment (tcouch) [reply mod_app/static/css/film.css:56]: Ignore this, I thought I was looking at the admin page.

File: mod_app/utils/extract_citations.py [hunk 10]
```diff
@@ -0,0 +1,36 @@
...
+        # for each citation found add the bit item to the bibliography
+        for short_citation in short_citations:
+            bibitem = BibliographyItem.objects.filter(
+                short_citation=short_citation
+            ).first()
+            if bibitem:
+                self.bibliography.add(bibitem)
+
+
+def extract_short_citations(field):
```
[the remark this answers is not in the document]
Comment (acholyn) [reply mod_app/utils/extract_citations.py:17]: it should've just been inserting it within <strong> tags anyway but I can add the class

File: mod_app/templates/base.html [hunk 11]
```diff
@@ -61,45 +59,57 @@
...
+                        <li>
+                            <a href="{% url 'film_list' %}">
+                                Films</a></li>
+                        <li><a href="{% url 'analysis_list' %}">
+                            Analyses: Critical Essays and Discussions</a></li>
+                        <li><a href="{% url 'bibliography' %}">
+                            Bibliography</a><?li>
+                            <li><a href="{% url 'tr_list' %}">
+                                Teaching Resources Available</a></li>
+                        </ul>
```
[the remark this answers is not in the document]
Comment (acholyn) [reply mod_app/templates/base.html:73]: interesting, shouldn't do that but good to know!

File: mod_app/models/film_model.py [hunk 12]
```diff
@@ -147,5 +149,16 @@ def posters(self):
...
+    bibliography = models.ManyToManyField(BibliographyItem, related_name="films")
+
+    def clean(self, *args, **kwargs):
+        super().clean(*args, **kwargs)
+        validate_format_other(self.format_other, self.format_type)
+
+    def save(self, *args, **kwargs):
+        super().save(*args, **kwargs)
+
+        update_bibliography(self, self.print_comments)
```
[the remark this answers is not in the document]
Comment (acholyn) [reply mod_app/models/film_model.py:110]: I will try to remove it from them but otherwise I'd prefer to have confirmation from the researchers if it looks like it's going to result in a lot of new code

File: mod_app/static/css/film.css (hunk 4 above)
Comment (acholyn) [reply mod_app/static/css/film.css:44]: it's part of the detail page - it's for a <dl> element

File: mod_app/utils/extract_citations.py (hunk 10 above)
[the remark this answers is not in the document]
Comment (acholyn) [reply mod_app/utils/extract_citations.py:17]: I've fixed the issue - I forgot to update the original insert after noticing the editor interprets it as `strong` and not `b`

File: mod_app/templates/film_detail.html (hunk 9 above)
Comment (acholyn) [reply mod_app/templates/film_detail.html:32]: That might be a browser-specific problem but also good to know. It works on chrome, brave and safari, which browser are you seeing the issue with?

File: docs/AWScurrentSetup.md
[the remark this answers is not in the document]
Comment (acholyn) [reply docs/AWScurrentSetup.md:1]: I will do once I've confirmed it actually works (needs to be on staging)

File: mod_app/templates/film_detail.html (hunk 9 above)
Comment (tcouch) [reply mod_app/templates/film_detail.html:32]: Firefox

Comment (tcouch) [reply mod_app/templates/film_detail.html:32]: Just tried it on Chrome: non-selected tabs are visible, but still very faint. Also the film list table looks waaay better on Chrome.
